init

diff --git a/scripts/package/Makefile b/scripts/package/Makefile
--- a/scripts/package/Makefile
+++ b/scripts/package/Makefile
@@ -1,4 +1,3 @@
-# SPDX-License-Identifier: GPL-2.0-only
 # Makefile for the different targets used to generate full packages of a kernel
 # It uses the generic clean infrastructure of kbuild
 
@@ -25,7 +24,6 @@
 # Remove hyphens since they have special meaning in RPM filenames
 KERNELPATH := kernel-$(subst -,_,$(KERNELRELEASE))
 KDEB_SOURCENAME ?= linux-$(KERNELRELEASE)
-KBUILD_PKG_ROOTCMD ?="fakeroot -u"
 export KDEB_SOURCENAME
 # Include only those top-level files that are needed by make, plus the GPL copy
 TAR_CONTENT := $(KBUILD_ALLDIRS) .config .scmversion Makefile \
@@ -35,12 +33,9 @@ MKSPEC     := $(srctree)/scripts/package/mkspec
 quiet_cmd_src_tar = TAR     $(2).tar.gz
       cmd_src_tar = \
 if test "$(objtree)" != "$(srctree)"; then \
-	echo >&2; \
-	echo >&2 "  ERROR:"; \
-	echo >&2 "  Building source tarball is not possible outside the"; \
-	echo >&2 "  kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
-	echo >&2 "  binrpm-pkg or bindeb-pkg target instead."; \
-	echo >&2; \
+	echo "Building source tarball is not possible outside the"; \
+	echo "kernel source tree. Don't set KBUILD_OUTPUT, or use the"; \
+	echo "binrpm-pkg or bindeb-pkg target instead."; \
 	false; \
 fi ; \
 $(srctree)/scripts/setlocalversion --save-scmversion; \
@@ -50,61 +45,65 @@ rm -f $(objtree)/.scmversion
 
 # rpm-pkg
 # ---------------------------------------------------------------------------
-rpm-pkg: FORCE
+rpm-pkg rpm: FORCE
 	$(MAKE) clean
 	$(CONFIG_SHELL) $(MKSPEC) >$(objtree)/kernel.spec
 	$(call cmd,src_tar,$(KERNELPATH),kernel.spec)
-	+rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz \
-	--define='_smp_mflags %{nil}'
+	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+	mv -f $(objtree)/.tmp_version $(objtree)/.version
+	rpmbuild $(RPMOPTS) --target $(UTS_MACHINE) -ta $(KERNELPATH).tar.gz
+	rm $(KERNELPATH).tar.gz kernel.spec
 
 # binrpm-pkg
 # ---------------------------------------------------------------------------
 binrpm-pkg: FORCE
-	$(MAKE) -f $(srctree)/Makefile
+	$(MAKE) KBUILD_SRC=
 	$(CONFIG_SHELL) $(MKSPEC) prebuilt > $(objtree)/binkernel.spec
-	+rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
-		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+	$(CONFIG_SHELL) $(srctree)/scripts/mkversion > $(objtree)/.tmp_version
+	mv -f $(objtree)/.tmp_version $(objtree)/.version
 
-clean-files += $(objtree)/*.spec
+	rpmbuild $(RPMOPTS) --define "_builddir $(objtree)" --target \
+		$(UTS_MACHINE) -bb $(objtree)/binkernel.spec
+	rm binkernel.spec
+
+# Deb target
+# ---------------------------------------------------------------------------
+quiet_cmd_builddeb = BUILDDEB
+      cmd_builddeb = set -e; \
+	test `id -u` = 0 || \
+	test -n "$(KBUILD_PKG_ROOTCMD)" || { \
+		which fakeroot >/dev/null 2>&1 && \
+		KBUILD_PKG_ROOTCMD="fakeroot -u"; \
+	} || { \
+		echo; \
+		echo "builddeb must be run as root (or using fakeroot)."; \
+		echo "KBUILD_PKG_ROOTCMD is unset and fakeroot not found."; \
+		echo "Try setting KBUILD_PKG_ROOTCMD to a command to acquire"; \
+		echo "root privileges (e.g., 'fakeroot -u' or 'sudo')."; \
+		false; \
+	} && \
+	\
+	$$KBUILD_PKG_ROOTCMD $(CONFIG_SHELL) \
+		$(srctree)/scripts/package/builddeb $@
 
 deb-pkg: FORCE
 	$(MAKE) clean
-	$(CONFIG_SHELL) $(srctree)/scripts/package/mkdebian
 	$(call cmd,src_tar,$(KDEB_SOURCENAME))
-	origversion=$$(dpkg-parsechangelog -SVersion |sed 's/-[^-]*$$//');\
-		mv $(KDEB_SOURCENAME).tar.gz ../$(KDEB_SOURCENAME)_$${origversion}.orig.tar.gz
-	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) $(DPKG_FLAGS) -i.git -us -uc
+	$(MAKE) KBUILD_SRC=
+	+$(call cmd,builddeb)
 
 bindeb-pkg: FORCE
-	$(CONFIG_SHELL) $(srctree)/scripts/package/mkdebian
-	+dpkg-buildpackage -r$(KBUILD_PKG_ROOTCMD) -a$$(cat debian/arch) $(DPKG_FLAGS) -b -nc -uc
-
-intdeb-pkg: FORCE
-	+$(CONFIG_SHELL) $(srctree)/scripts/package/builddeb
+	$(MAKE) KBUILD_SRC=
+	+$(call cmd,builddeb)
 
 clean-dirs += $(objtree)/debian/
 
-# snap-pkg
-# ---------------------------------------------------------------------------
-snap-pkg: FORCE
-	rm -rf $(objtree)/snap
-	mkdir $(objtree)/snap
-	$(MAKE) clean
-	$(call cmd,src_tar,$(KERNELPATH))
-	sed "s@KERNELRELEASE@$(KERNELRELEASE)@; \
-		s@SRCTREE@$(shell realpath $(KERNELPATH).tar.gz)@" \
-		$(srctree)/scripts/package/snapcraft.template > \
-		$(objtree)/snap/snapcraft.yaml
-	cd $(objtree)/snap && \
-	snapcraft --target-arch=$(UTS_MACHINE)
-
-clean-dirs += $(objtree)/snap/
 
 # tarball targets
 # ---------------------------------------------------------------------------
 tar%pkg: FORCE
-	$(MAKE) -f $(srctree)/Makefile
-	+$(CONFIG_SHELL) $(srctree)/scripts/package/buildtar $@
+	$(MAKE) KBUILD_SRC=
+	$(CONFIG_SHELL) $(srctree)/scripts/package/buildtar $@
 
 clean-dirs += $(objtree)/tar-install/
 
@@ -143,7 +142,6 @@ help: FORCE
 	@echo '  binrpm-pkg          - Build only the binary kernel RPM package'
 	@echo '  deb-pkg             - Build both source and binary deb kernel packages'
 	@echo '  bindeb-pkg          - Build only the binary kernel deb package'
-	@echo '  snap-pkg            - Build only the binary kernel snap package (will connect to external hosts)'
 	@echo '  tar-pkg             - Build the kernel as an uncompressed tarball'
 	@echo '  targz-pkg           - Build the kernel as a gzip compressed tarball'
 	@echo '  tarbz2-pkg          - Build the kernel as a bzip2 compressed tarball'
diff --git a/tools/testing/selftests/ftrace/ftracetest b/tools/testing/selftests/ftrace/ftracetest
--- a/tools/testing/selftests/ftrace/ftracetest
+++ b/tools/testing/selftests/ftrace/ftracetest
@@ -1,37 +1,26 @@
 #!/bin/sh
-# SPDX-License-Identifier: GPL-2.0-only
 
 # ftracetest - Ftrace test shell scripts
 #
 # Copyright (C) Hitachi Ltd., 2014
 #  Written by Masami Hiramatsu <masami.hiramatsu.pt@hitachi.com>
 #
+# Released under the terms of the GPL v2.
 
 usage() { # errno [message]
-[ ! -z "$2" ] && echo $2
+[ "$2" ] && echo $2
 echo "Usage: ftracetest [options] [testcase(s)] [testcase-directory(s)]"
 echo " Options:"
 echo "		-h|--help  Show help message"
 echo "		-k|--keep  Keep passed test logs"
-echo "		-v|--verbose Increase verbosity of test messages"
-echo "		-vv        Alias of -v -v (Show all results in stdout)"
-echo "		-vvv       Alias of -v -v -v (Show all commands immediately)"
-echo "		--fail-unsupported Treat UNSUPPORTED as a failure"
+echo "		-v|--verbose Show all stdout messages in testcases"
 echo "		-d|--debug Debug mode (trace all shell commands)"
-echo "		-l|--logdir <dir> Save logs on the <dir>"
-echo "		            If <dir> is -, all logs output in console only"
 exit $1
 }
 
-# default error
-err_ret=1
-
-# kselftest skip code is 4
-err_skip=4
-
 errexit() { # message
   echo "Error: $1" 1>&2
-  exit $err_ret
+  exit 1
 }
 
 # Ensuring user privilege
@@ -56,7 +45,7 @@ parse_opts() { # opts
   local OPT_TEST_CASES=
   local OPT_TEST_DIR=
 
-  while [ ! -z "$1" ]; do
+  while [ "$1" ]; do
     case "$1" in
     --help|-h)
       usage 0
@@ -65,37 +54,13 @@ parse_opts() { # opts
       KEEP_LOG=1
       shift 1
     ;;
-    --verbose|-v|-vv|-vvv)
-      if [ $VERBOSE -eq -1 ]; then
-	usage "--console can not use with --verbose"
-      fi
-      VERBOSE=$((VERBOSE + 1))
-      [ $1 = '-vv' ] && VERBOSE=$((VERBOSE + 1))
-      [ $1 = '-vvv' ] && VERBOSE=$((VERBOSE + 2))
-      shift 1
-    ;;
-    --console)
-      if [ $VERBOSE -ne 0 ]; then
-	usage "--console can not use with --verbose"
-      fi
-      VERBOSE=-1
+    --verbose|-v)
+      VERBOSE=1
       shift 1
     ;;
     --debug|-d)
       DEBUG=1
       shift 1
-    ;;
-    --stop-fail)
-      STOP_FAILURE=1
-      shift 1
-    ;;
-    --fail-unsupported)
-      UNSUPPORTED_RESULT=1
-      shift 1
-    ;;
-    --logdir|-l)
-      LOG_DIR=$2
-      shift 2
     ;;
     *.tc)
       if [ -f "$1" ]; then
@@ -116,37 +81,17 @@ parse_opts() { # opts
     ;;
     esac
   done
-  if [ ! -z "$OPT_TEST_CASES" ]; then
+  if [ "$OPT_TEST_CASES" ]; then
     TEST_CASES=$OPT_TEST_CASES
   fi
 }
 
 # Parameters
-TRACING_DIR=`grep tracefs /proc/mounts | cut -f2 -d' ' | head -1`
-if [ -z "$TRACING_DIR" ]; then
-    DEBUGFS_DIR=`grep debugfs /proc/mounts | cut -f2 -d' ' | head -1`
-    if [ -z "$DEBUGFS_DIR" ]; then
-	# If tracefs exists, then so does /sys/kernel/tracing
-	if [ -d "/sys/kernel/tracing" ]; then
-	    mount -t tracefs nodev /sys/kernel/tracing ||
-	      errexit "Failed to mount /sys/kernel/tracing"
-	    TRACING_DIR="/sys/kernel/tracing"
-	# If debugfs exists, then so does /sys/kernel/debug
-	elif [ -d "/sys/kernel/debug" ]; then
-	    mount -t debugfs nodev /sys/kernel/debug ||
-	      errexit "Failed to mount /sys/kernel/debug"
-	    TRACING_DIR="/sys/kernel/debug/tracing"
-	else
-	    err_ret=$err_skip
-	    errexit "debugfs and tracefs are not configured in this kernel"
-	fi
-    else
-	TRACING_DIR="$DEBUGFS_DIR/tracing"
-    fi
-fi
-if [ ! -d "$TRACING_DIR" ]; then
-    err_ret=$err_skip
-    errexit "ftrace is not configured in this kernel"
+DEBUGFS_DIR=`grep debugfs /proc/mounts | cut -f2 -d' ' | head -1`
+if [ -z "$DEBUGFS_DIR" ]; then
+    TRACING_DIR=`grep tracefs /proc/mounts | cut -f2 -d' ' | head -1`
+else
+    TRACING_DIR=$DEBUGFS_DIR/tracing
 fi
 
 TOP_DIR=`absdir $0`
@@ -156,8 +101,6 @@ LOG_DIR=$TOP_DIR/logs/`date +%Y%m%d-%H%M%S`/
 KEEP_LOG=0
 DEBUG=0
 VERBOSE=0
-UNSUPPORTED_RESULT=0
-STOP_FAILURE=0
 # Parse command-line options
 parse_opts $*
 
@@ -169,47 +112,14 @@ if [ -z "$TRACING_DIR" -o ! -d "$TRACING_DIR" ]; then
 fi
 
 # Preparing logs
-if [ "x$LOG_DIR" = "x-" ]; then
-  LOG_FILE=
-  date
-else
-  LOG_FILE=$LOG_DIR/ftracetest.log
-  mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
-  date > $LOG_FILE
-fi
-
-# Define text colors
-# Check available colors on the terminal, if any
-ncolors=`tput colors 2>/dev/null || echo 0`
-color_reset=
-color_red=
-color_green=
-color_blue=
-# If stdout exists and number of colors is eight or more, use them
-if [ -t 1 -a "$ncolors" -ge 8 ]; then
-  color_reset="\033[0m"
-  color_red="\033[31m"
-  color_green="\033[32m"
-  color_blue="\033[34m"
-fi
-
-strip_esc() {
-  # busybox sed implementation doesn't accept "\x1B", so use [:cntrl:] instead.
-  sed -E "s/[[:cntrl:]]\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
-}
-
+LOG_FILE=$LOG_DIR/ftracetest.log
+mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
+date > $LOG_FILE
 prlog() { # messages
-  newline="\n"
-  if [ "$1" = "-n" ] ; then
-    newline=
-    shift
-  fi
-  printf "$*$newline"
-  [ "$LOG_FILE" ] && printf "$*$newline" | strip_esc >> $LOG_FILE
+  echo "$@" | tee -a $LOG_FILE
 }
 catlog() { #file
-  cat $1
-  [ "$LOG_FILE" ] && cat $1 | strip_esc >> $LOG_FILE
+  cat $1 | tee -a $LOG_FILE
 }
 prlog "=== Ftrace unit tests ==="
 
@@ -233,52 +143,47 @@ XFAILED_CASES=
 UNDEFINED_CASES=
 TOTAL_RESULT=0
 
-INSTANCE=
 CASENO=0
 testcase() { # testfile
   CASENO=$((CASENO+1))
   desc=`grep "^#[ \t]*description:" $1 | cut -f2 -d:`
-  prlog -n "[$CASENO]$INSTANCE$desc"
-}
-
-test_on_instance() { # testfile
-  grep -q "^#[ \t]*flags:.*instance" $1
+  prlog -n "[$CASENO]$desc"
 }
 
 eval_result() { # sigval
   case $1 in
     $PASS)
-      prlog "	[${color_green}PASS${color_reset}]"
+      prlog "	[PASS]"
       PASSED_CASES="$PASSED_CASES $CASENO"
       return 0
     ;;
     $FAIL)
-      prlog "	[${color_red}FAIL${color_reset}]"
+      prlog "	[FAIL]"
       FAILED_CASES="$FAILED_CASES $CASENO"
       return 1 # this is a bug.
     ;;
     $UNRESOLVED)
-      prlog "	[${color_blue}UNRESOLVED${color_reset}]"
+      prlog "	[UNRESOLVED]"
       UNRESOLVED_CASES="$UNRESOLVED_CASES $CASENO"
       return 1 # this is a kind of bug.. something happened.
     ;;
     $UNTESTED)
-      prlog "	[${color_blue}UNTESTED${color_reset}]"
+      prlog "	[UNTESTED]"
       UNTESTED_CASES="$UNTESTED_CASES $CASENO"
       return 0
     ;;
     $UNSUPPORTED)
-      prlog "	[${color_blue}UNSUPPORTED${color_reset}]"
+      prlog "	[UNSUPPORTED]"
       UNSUPPORTED_CASES="$UNSUPPORTED_CASES $CASENO"
-      return $UNSUPPORTED_RESULT # depends on use case
+      return 1 # this is not a bug, but the result should be reported.
     ;;
     $XFAIL)
-      prlog "	[${color_red}XFAIL${color_reset}]"
+      prlog "	[XFAIL]"
       XFAILED_CASES="$XFAILED_CASES $CASENO"
       return 0
     ;;
     *)
-      prlog "	[${color_blue}UNDEFINED${color_reset}]"
+      prlog "	[UNDEFINED]"
       UNDEFINED_CASES="$UNDEFINED_CASES $CASENO"
       return 1 # this must be a test bug
     ;;
@@ -290,14 +195,7 @@ SIG_RESULT=
 SIG_BASE=36	# Use realtime signals
 SIG_PID=$$
 
-exit_pass () {
-  exit 0
-}
-
 SIG_FAIL=$((SIG_BASE + FAIL))
-exit_fail () {
-  exit 1
-}
 trap 'SIG_RESULT=$FAIL' $SIG_FAIL
 
 SIG_UNRESOLVED=$((SIG_BASE + UNRESOLVED))
@@ -330,30 +228,18 @@ trap 'SIG_RESULT=$XFAIL' $SIG_XFAIL
 
 __run_test() { # testfile
   # setup PID and PPID, $$ is not updated.
-  (cd $TRACING_DIR; read PID _ < /proc/self/stat; set -e; set -x; initialize_ftrace; . $1)
+  (cd $TRACING_DIR; read PID _ < /proc/self/stat ; set -e; set -x; . $1)
   [ $? -ne 0 ] && kill -s $SIG_FAIL $SIG_PID
 }
 
 # Run one test case
 run_test() { # testfile
   local testname=`basename $1`
+  local testlog=`mktemp $LOG_DIR/${testname}-log.XXXXXX`
   testcase $1
-  if [ ! -z "$LOG_FILE" ] ; then
-    local testlog=`mktemp $LOG_DIR/${CASENO}-${testname}-log.XXXXXX`
-  else
-    local testlog=/proc/self/fd/1
-  fi
-  export TMPDIR=`mktemp -d /tmp/ftracetest-dir.XXXXXX`
-  export FTRACETEST_ROOT=$TOP_DIR
-  echo "execute$INSTANCE: "$1 > $testlog
+  echo "execute: "$1 > $testlog
   SIG_RESULT=0
-  if [ $VERBOSE -eq -1 ]; then
-    __run_test $1
-  elif [ -z "$LOG_FILE" ]; then
-    __run_test $1 2>&1
-  elif [ $VERBOSE -ge 3 ]; then
-    __run_test $1 | tee -a $testlog 2>&1
-  elif [ $VERBOSE -eq 2 ]; then
+  if [ $VERBOSE -ne 0 ]; then
     __run_test $1 2>> $testlog | tee -a $testlog
   else
     __run_test $1 >> $testlog 2>&1
@@ -361,12 +247,11 @@ run_test() { # testfile
   eval_result $SIG_RESULT
   if [ $? -eq 0 ]; then
     # Remove test log if the test was done as it was expected.
-    [ $KEEP_LOG -eq 0 -a ! -z "$LOG_FILE" ] && rm $testlog
+    [ $KEEP_LOG -eq 0 ] && rm $testlog
   else
-    [ $VERBOSE -eq 1 -o $VERBOSE -eq 2 ] && catlog $testlog
+    catlog $testlog
     TOTAL_RESULT=1
   fi
-  rm -rf $TMPDIR
 }
 
 # load in the helper functions
@@ -375,27 +260,7 @@ run_test() { # testfile
 # Main loop
 for t in $TEST_CASES; do
   run_test $t
-  if [ $STOP_FAILURE -ne 0 -a $TOTAL_RESULT -ne 0 ]; then
-    echo "A failure detected. Stop test."
-    exit 1
-  fi
 done
-
-# Test on instance loop
-INSTANCE=" (instance) "
-for t in $TEST_CASES; do
-  test_on_instance $t || continue
-  SAVED_TRACING_DIR=$TRACING_DIR
-  export TRACING_DIR=`mktemp -d $TRACING_DIR/instances/ftracetest.XXXXXX`
-  run_test $t
-  rmdir $TRACING_DIR
-  TRACING_DIR=$SAVED_TRACING_DIR
-  if [ $STOP_FAILURE -ne 0 -a $TOTAL_RESULT -ne 0 ]; then
-    echo "A failure detected. Stop test."
-    exit 1
-  fi
-done
-(cd $TRACING_DIR; initialize_ftrace) # for cleanup
 
 prlog ""
 prlog "# of passed: " `echo $PASSED_CASES | wc -w`
